index:
  path: /
  controller: App\Controllers\DefaultController::index

api_players_create:
  path: /v1/players
  controller: App\Controllers\DefaultController::index
  methods: [POST, GET]

api_players_update:
  path: /v1/players/{playerId}/{test}
  controller: App\Controllers\DefaultController::index
