index:
  path: /
  controller: App\Controllers\DefaultController::index

api_leaderboards_options:
  path: /v1/leaderboards
  controller: App\Controllers\DefaultController::options
  methods: [OPTIONS]

api_leaderboards_list:
  path: /v1/leaderboards
  controller: App\Controllers\V1\LeaderboardsController::list
  methods: [GET]

api_auth_options:
  path: /v1/login
  controller: App\Controllers\DefaultController::options
  methods: [OPTIONS]

api_auth_login:
  path: /v1/login
  controller: App\Controllers\V1\AuthController::login
  methods: [POST]

api_player_options:
  path: /v1/player
  controller: App\Controllers\DefaultController::options
  methods: [OPTIONS]

api_player_create:
  path: /v1/player
  controller: App\Controllers\V1\RegisterController::create
  methods: [POST]

api_player_show:
  path: /v1/player
  controller: App\Controllers\V1\PlayerController::show
  methods: [GET]

api_player_update:
  path: /v1/player
  controller: App\Controllers\V1\PlayerController::update
  methods: [PUT]

api_achievements_options:
  path: /v1/player/achievements
  controller: App\Controllers\DefaultController::options
  methods: [OPTIONS]

api_achievements_show:
  path: /v1/player/achievements
  controller: App\Controllers\V1\AchievementsController::show
  methods: [GET]

api_game_options:
  path: /v1/player/game
  controller: App\Controllers\DefaultController::options
  methods: [OPTIONS]

api_game_start:
  path: /v1/player/game
  controller: App\Controllers\V1\GameController::start
  methods: [POST]

api_games_options:
    path: /v1/player/game/{gameId}
    controller: App\Controllers\DefaultController::options
    methods: [OPTIONS]

api_game_play:
  path: /v1/player/game/{gameId}
  controller: App\Controllers\V1\GameController::play
  methods: [PUT]

api_game_end:
  path: /v1/player/game/{gameId}
  controller: App\Controllers\V1\GameController::end
  methods: [DELETE]
