index:
  path: /
  controller: App\Controllers\DefaultController::index

api_player_create:
  path: /v1/player
  controller: App\Controllers\V1\RegisterController::create
  methods: [POST]

api_player_login:
  path: /v1/player
  controller: App\Controllers\V1\AuthController::login
  methods: [POST]

api_player_show:
  path: /v1/player
  controller: App\Controllers\V1\PlayerController::show
  methods: [GET]

api_player_update:
  path: /v1/player
  controller: App\Controllers\V1\PlayerController::update
  methods: [PUT]

api_game_create:
  path: /v1/player/game
  controller: App\Controllers\V1\GameController::create
  methods: [POST]

api_game_show:
  path: /v1/player/game
  controller: App\Controllers\V1\GameController::show
  methods: [GET]

api_game_update:
  path: /v1/player/game
  controller: App\Controllers\V1\GameController::update
  methods: [PUT]
